# Generated by Django 3.2.9 on 2022-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_models', models.CharField(max_length=255, verbose_name='Модель телефона')),
                ('imei', models.CharField(max_length=255, unique=True, verbose_name='IMEI телефона')),
                ('organization', models.CharField(max_length=255, verbose_name='Инициатор')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить данные',
                'ordering': ['-created'],
            },
        ),
    ]
