# Generated by Django 3.2.9 on 2022-02-24 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='erp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ЕРП'),
        ),
        migrations.AddField(
            model_name='base',
            name='num',
            field=models.IntegerField(default=1, max_length=16, verbose_name='Номер инициатора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base',
            name='imei',
            field=models.IntegerField(default=14, unique=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(15)], verbose_name='IMEI телефона'),
        ),
    ]
