# Generated by Django 3.2.9 on 2022-02-24 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20220224_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='imei',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(14)], verbose_name='IMEI телефона'),
        ),
        migrations.AlterField(
            model_name='base',
            name='num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Номер инициатора'),
        ),
    ]
