# Generated by Django 3.2.9 on 2022-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_alter_base_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
